/**
 * Render the plugin's settings into the `config.py` the bridge process loads.
 *
 * The DSH settings card is the single source of truth for wake words, routing
 * and voice; the bridge is a separate Python process that reads a `config.py`.
 * This module bridges the two: it writes a generated `config.py` into the plugin
 * data directory and the supervisor points the child at it through
 * `CONFIG_PATH` (`bridge/core/utils/config_loader.py` honours that variable).
 *
 * The generated file is an overlay, not a copy: it loads the repository's
 * `bridge/config.py` template as a module and deep-merges the settings on top,
 * so defaults and the `before_wakeup` / `after_wakeup` hooks stay in one place
 * upstream and are never duplicated (and never silently stale) here.
 *
 * Writes are atomic — temp file plus `renameSync` — because the bridge polls
 * this file's mtime once a second and reloads it; a half-written file would make
 * it log a reload failure (or, worse, load a truncated config). On Windows that
 * rename can be refused while the bridge is inside its read window (measured at
 * roughly 0.2 ms, once a second), so the install retries instead of reporting a
 * failure the page would not notice.
 * @module dsh-xiaoai-bridge/render-config
 */
import { renameSync, unlinkSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/** File name of the rendered config inside the plugin data directory. */
export const CONFIG_FILE_NAME = 'config.py';

/** Marker on line 1 of the generated file; the bridge ignores it. */
export const GENERATED_HEADER = '# Generated by dsh-xiaoai-bridge — do not edit.';

/** How many times the atomic install retries a rename the OS refused. */
export const RENAME_ATTEMPTS = 40;

/** Pause between those attempts, in milliseconds (a full round measures ≈0.6 s on Windows). */
export const RENAME_RETRY_MS = 5;

/** @param {number} ms block this thread for a moment */
function sleepSync(ms) {
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);
}

/**
 * Install the rendered file, tolerating Windows' transient refusals.
 *
 * The bridge hot-reloads by reading the file, and the measured read window is
 * about 0.2 ms out of every second; `renameSync` onto a file inside that window
 * raises EPERM/EACCES/EBUSY (reproduced with a foreign handle opened without
 * FILE_SHARE_DELETE). A bounded synchronous retry is the whole fix: the callers
 * are synchronous, the window is tiny, and a failed render must not be mistaken
 * for a saved setting. Any other error is a real one and is rethrown.
 * @param {string} from temp file path
 * @param {string} to destination path
 */
function installAtomically(from, to) {
  const transient = new Set(['EPERM', 'EACCES', 'EBUSY']);
  for (let attempt = 0; attempt < RENAME_ATTEMPTS; attempt += 1) {
    try {
      renameSync(from, to);
      return;
    } catch (err) {
      const tooMany = attempt === RENAME_ATTEMPTS - 1;
      if (tooMany || !transient.has(String(err?.code))) {
        try {
          unlinkSync(from);
        } catch {
          // The half-written temp file is classified as generated and removed
          // by cleanup; failing to remove it here must not hide the real error.
        }
        throw err;
      }
      sleepSync(RENAME_RETRY_MS);
    }
  }
}

/**
 * Settings value to bridge provider, for the providers the bridge can load.
 *
 * The settings page also offers the reserved `mimo` choice, which is missing on
 * purpose: the bridge's TTS router raises on a provider it has no client for, so
 * writing `mimo` would break playback rather than reserve it. An empty value is
 * missing too — that is the router's own "pick by voice id" rule.
 */
export const RENDERED_TTS_PROVIDERS = Object.freeze({ xiaoai: 'xiaoai' });

/**
 * Absolute path of the rendered config.
 * @param {string} dataDir plugin data directory
 * @returns {string} `<dataDir>/config.py`
 */
export function renderConfigPath(dataDir) {
  return join(dataDir, CONFIG_FILE_NAME);
}

/**
 * Split one of the settings' "one per line" lists.
 *
 * Commas are accepted too: the schema stores wake words and exit words as plain
 * text, and a user typing `小爱小爱, 小爱同学` should not get a wake word with a
 * comma in it.
 *
 * The full-width separators (`,`, `、`) and a bare carriage return matter for
 * wake words specifically: this list lands in `wakeup.keywords`, the bridge
 * feeds each entry to sherpa-onnx, and an entry that still carries a full-width
 * comma is not a word sherpa can score -- the keyword is then dropped silently,
 * so the speaker simply never wakes. There is exactly one splitter for these
 * fields on purpose (`parseWakeKeywords` in `lib/index.js` delegates here); two
 * of them drifting is how that bug happened.
 * @param {unknown} value raw settings text
 * @returns {string[]} non-empty, trimmed entries in order
 */
export function splitList(value) {
  if (typeof value !== 'string') return [];
  return value
    .split(/[\r\n,，、]+/)
    .map((item) => item.trim())
    .filter((item) => item.length > 0);
}

/**
 * Render a JavaScript value as a Python literal.
 *
 * JSON is *almost* Python; only `true` / `false` / `null` differ, and every
 * escape `JSON.stringify` emits for a string is a valid Python escape too.
 * @param {unknown} value any JSON-shaped value
 * @returns {string} Python source for that value
 */
export function pythonLiteral(value) {
  if (value === null || value === undefined) return 'None';
  if (typeof value === 'boolean') return value ? 'True' : 'False';
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) throw new Error('dsh-xiaoai-bridge: refusing to render a non-finite number');
    return String(value);
  }
  if (typeof value === 'string') return JSON.stringify(value);
  if (Array.isArray(value)) return '[' + value.map(pythonLiteral).join(', ') + ']';
  if (typeof value === 'object') {
    const entries = Object.entries(value)
      .filter(([, item]) => item !== undefined)
      .map(([key, item]) => `${JSON.stringify(key)}: ${pythonLiteral(item)}`);
    return '{' + entries.join(', ') + '}';
  }
  throw new Error(`dsh-xiaoai-bridge: cannot render a ${typeof value} as a Python literal`);
}

/**
 * Compose the text the bridge appends to every utterance of a voice session.
 *
 * The voice rule and the agent's behavior style travel together: the bridge
 * appends this string to each delivered utterance, which is the one channel
 * that reaches the speaker's session alone. Adding prompt text by rebuilding
 * the session's prompt assembly is explicitly discouraged by the host's own
 * plugin practices, and a profile-wide prompt section would leak into every
 * desktop session.
 * @param {{voiceRuleText?: string, behaviorStyle?: string}} cfg settings
 * @returns {string} the appended rule text, '' when both parts are empty
 */
export function composeVoiceRule({ voiceRuleText, behaviorStyle } = {}) {
  const rule = typeof voiceRuleText === 'string' ? voiceRuleText.trim() : '';
  const behavior = typeof behaviorStyle === 'string' ? behaviorStyle.trim() : '';
  if (rule.length === 0) return behavior;
  if (behavior.length === 0) return rule;
  return `${rule}\n\n行动准则：${behavior}`;
}

/**
 * Turn the settings into the overlay that is merged onto the bridge template.
 *
 * Only fields the plugin owns appear here: anything absent keeps the template's
 * own default, which is what makes an emptied settings field mean "use the
 * upstream default" rather than "write an empty value".
 * @param {object} cfg plain plugin config (see `resolveLoadConfig`)
 * @returns {object} nested overrides matching `APP_CONFIG`'s shape
 */
export function buildOverrides(cfg) {
  const wakeKeywords = splitList(cfg?.wakeKeywords);
  const exitKeywords = splitList(cfg?.exitKeywords);

  const wakeup = {};
  if (wakeKeywords.length > 0) wakeup.keywords = wakeKeywords;
  if (Number.isFinite(cfg?.wakeupTimeout)) wakeup.timeout = cfg.wakeupTimeout;

  const dsh = {};
  if (wakeKeywords.length > 0) dsh.wakeup_keywords = wakeKeywords;
  if (exitKeywords.length > 0) dsh.exit_keywords = exitKeywords;
  for (const [key, value] of Object.entries({
    session_key: cfg?.sessionKey,
    device_name: cfg?.deviceName,
    tts_speaker: cfg?.ttsSpeaker,
    wakeup_reply: cfg?.wakeupReplyText,
    exit_reply: cfg?.exitReplyText,
    fallback_text: cfg?.fallbackText,
    rule_prompt_for_skill: composeVoiceRule(cfg),
  })) {
    if (typeof value === 'string' && value.length > 0) dsh[key] = value;
  }
  // A boolean the settings page owns outright, so it is rendered even when
  // false: leaving it out would mean "whatever the template says", and the
  // page's own default (single-shot) is the one that must win.
  if (typeof cfg?.continuousConversation === 'boolean') {
    dsh.continuous_conversation = cfg.continuousConversation;
  }
  // Only a provider the bridge can load is written; see RENDERED_TTS_PROVIDERS.
  const ttsProvider = RENDERED_TTS_PROVIDERS[cfg?.ttsProvider];
  if (ttsProvider) dsh.tts_provider = ttsProvider;

  const asr = {};
  if (typeof cfg?.asrBackend === 'string' && cfg.asrBackend.length > 0) asr.model = cfg.asrBackend;

  const overrides = {};
  if (Object.keys(wakeup).length > 0) overrides.wakeup = wakeup;
  if (Object.keys(dsh).length > 0) overrides.dsh = dsh;
  if (Object.keys(asr).length > 0) overrides.asr = asr;
  return overrides;
}

/**
 * Render the whole generated `config.py`.
 * @param {{templatePath: string, overrides: object}} options render inputs
 * @returns {string} Python source
 */
export function renderConfigSource({ templatePath, overrides }) {
  return [
    GENERATED_HEADER,
    "# 设置页保存后本文件会被重新渲染；桥接器每秒轮询它的 mtime 并热重载。",
    'import importlib.util as _importlib_util',
    'from pathlib import Path as _Path',
    '',
    `_TEMPLATE_PATH = _Path(${pythonLiteral(templatePath)})`,
    '',
    '',
    'def _load_template(path):',
    '    """把仓库里的 config.py 当作模板模块加载。"""',
    '    spec = _importlib_util.spec_from_file_location("bridge_config_template", path)',
    '    module = _importlib_util.module_from_spec(spec)',
    '    spec.loader.exec_module(module)',
    '    return module',
    '',
    '',
    'def _deep_merge(target, patch):',
    '    """递归合并设置覆盖项，未覆盖的键保留模板默认值。"""',
    '    for key, value in patch.items():',
    '        if isinstance(value, dict) and isinstance(target.get(key), dict):',
    '            _deep_merge(target[key], value)',
    '        else:',
    '            target[key] = value',
    '    return target',
    '',
    '',
    '_template = _load_template(_TEMPLATE_PATH)',
    '',
    '# 与模板共用同一个字典对象，模板里的 before_wakeup/after_wakeup 才能看到覆盖值。',
    'APP_CONFIG = _template.APP_CONFIG',
    'before_wakeup = _template.before_wakeup',
    'after_wakeup = _template.after_wakeup',
    '',
    `_deep_merge(APP_CONFIG, ${pythonLiteral(overrides)})`,
    '',
  ].join('\n');
}

/**
 * Render and atomically install the bridge config.
 * @param {object} options write inputs
 * @param {string} options.dataDir plugin data directory
 * @param {string} options.templatePath repository `config.py` used as the template
 * @param {object} options.cfg plain plugin config
 * @param {import('node:fs').PathLike} [options.path] override the destination
 * @returns {{path: string, source: string, overrides: object}} what was written
 */
export function writeConfig({ dataDir, templatePath, cfg, path }) {
  const target = path ?? renderConfigPath(dataDir);
  const overrides = buildOverrides(cfg);
  const source = renderConfigSource({ templatePath, overrides });
  const tmp = `${target}.tmp`;
  writeFileSync(tmp, source, 'utf8');
  installAtomically(tmp, target);
  return { path: target, source, overrides };
}
